import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const spaceGrotesk = localFont({
  src: "../SpaceGroteskTrimmed.woff2",
  display: "block",
  fallback: ["sans-serif"],
  adjustFontFallback: "Times New Roman",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body>
        <div>hi</div>
        <div className={inter.className}>{children}</div>
      </body>
    </html>
  );
}
